### ISSUE TITLE
Can I create multiple users to access the panel?

### ISSUE THREAD

**Issue by ManucrackYT** [jareer12/Discord-Bot-Dashboard#14]

**Comment by DairyWeb3638077** [comment]
Hey @ManucrackYT I wish I could help but I have an issue myself https://github.com/jareer12/Discord-Bot-Dashboard/issues/13. Could you help and maybe I could help you? Also, is there a discord for this?

**Comment by jareer12** [comment]
No, multiple users aren't possible. You can only have one username and one password that you're supposed to put in the `.env`.
