### ISSUE TITLE
Delete files isn't working

### ISSUE THREAD

**Issue by ManucrackYT** [jareer12/Discord-Bot-Dashboard#15]
When I try to delete a file from File Manager, it doesn't drops any error or message. It just doesn't do the action.

**Comment by jareer12** [comment]
Any errors in the console? `forever logs`

**Comment by ManucrackYT** [comment]
In host's console there isn't errors, the startup command I use is `node .`

**Comment by jareer12** [comment]
> In host's console there isn't errors, the startup command I use is `node .`

Maybe check `Network` in the developer tools panel? Delete a file from the UI and check for the response.

**Comment by ManucrackYT** [comment]
Where's developer tools panel?

**Comment by jareer12** [comment]
> Where's developer tools panel?

When your on the panel. You can press `F12` to open the dev tools.

**Comment by ManucrackYT** [comment]
![imagen](https://user-images.githubusercontent.com/71397795/194122883-69201b2b-50cd-4844-9ff3-fd152d100f6f.png)
This is what I get in Browser's console when clicking "delete selected" button

**Comment by ManucrackYT** [comment]
![imagen](https://user-images.githubusercontent.com/71397795/194351477-0c5beca7-3f65-4ca5-b905-14d70890e309.png)

**Comment by jareer12** [comment]
> ![imagen](https://user-images.githubusercontent.com/71397795/194351477-0c5beca7-3f65-4ca5-b905-14d70890e309.png)

The response section.

**Comment by ManucrackYT** [comment]
I think problem is because delete.html on pages folder is empty
