### ISSUE TITLE
fs/promises

### ISSUE THREAD

**Issue by ozcangyo** [jareer12/Discord-Bot-Dashboard#9]
Hello, As I mentioned in the title, when I try to install the "fs/promises" module missing, it freezes as in the image I have given below. (I waited for 5 minutes)

![image](https://user-images.githubusercontent.com/105934348/185147483-ebdc6351-3f22-4f5a-8e15-17fa39c1b3b1.png)

Need a help..

**Comment by jareer12** [comment]
```shell
npm install fs.promises
```

**Comment by jareer12** [comment]
```shell
npm install fs.promises
```
